apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cd
  namespace: wac-hospital
spec:
  wait: true
  interval: 42s
  path: clusters/localhost
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-repo