apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prepare
  namespace: wac-hospital
spec:
  wait: true
  interval: 120s
  path: clusters/localhost/prepare
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-repo