apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    app.kubernetes.io/part-of: wac-hospital
    app.kubernetes.io/name: mt-ambulance-wl

namespace: wac-hospital

resources:
- cd.kustomization.yaml
- install.kustomization.yaml
- git-repository.yaml