apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: mt-ambulance-ufe-content
spec:
  microFrontend: mt-ambulance-ufe
  element: mt-ambulance-wl-app
  attributes:
    - name: api-base
      value: http://localhost:30081/api
    - name: ambulance-id
      value: bobulova
    - name: base-path
      value: /mt-wac/
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?mt-wac(/.*)?$"