apiVersion: apps/v1
kind: Deployment
metadata:
  name: &PODNAME mongo-express
  annotations:
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: *PODNAME
  template:
    metadata:
      labels:
        pod: *PODNAME
    spec:
      containers:
      - image: mongo-express
        name: mongo-express
        env:
        - name: ME_CONFIG_SITE_BASEURL
          value: /mongo-express/
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-auth
              key: username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-auth
              key: password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongodb-connection
              key: host
        # authentication and authorization at cluster level
        - name: ME_CONFIG_BASICAUTH_USERNAME
          value: ""
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          value: ""
        - name: ME_CONFIG_BASICAUTH
          value: "false"
        ports:
        - name: http
          containerPort: 8081
        resources:
          limits:
            cpu: '1'
            memory: '512M'
          requests:
            cpu: '0.01'
            memory: '128M'